# This file is part of jtrees.
# https://github.com/someuser/somepackage

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2017, Chris and Zack <zackkollar@gmail.com>

language: python

python:
    - "3.6"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
